maintainer       "Joshua Peek"
maintainer_email "josh@joshpeek.com"
license          "MIT"
description      "Installs/configures GitHub"
version          "0.1.0"

depends "elasticsearch"
depends "erlang"
depends "gcc"
depends "git"
depends "homebrew"
depends "icu4c"
depends "memcached"
depends "mysql"
depends "node"
depends "openvpn"
depends "phantomjs"
depends "pow"
depends "python"
depends "qt"
depends "rbenv"
depends "redis"
depends "solr"

supports "mac_os_x"
